version: '3'
services:
  shell:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/src
    depends_on:
        - mongodb

  mongodb:
    image: mongo
    ports:
        - "127.0.0.1:27017:27017"
