version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.8
      - test-3.9
      - black

defaults: &defaults
  working_directory: ~/code
  environment:
    # circleci exposes services on localhost
    MONGODB_HOST: localhost
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: sudo pip install -r requirements.txt
  - run:
      name: Test
      command: pytest

jobs:
  test-3.8:
    <<: *defaults
    docker:
    - image: circleci/python:3.8
    - image: mongo
  test-3.9:
    <<: *defaults
    docker:
      - image: circleci/python:3.9
      - image: mongo
  black:
    working_directory: ~/code
    docker:
    - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip install black
      - run:
          name: Check formatting
          command: black --check .
